version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todosdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - app_network  
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - mysql_data:/var/lib/mysql



  api:
    build: . 
    container_name: dotnet_api_container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=todosdb;User=myuser;Password=mypassword;"
    networks:
      - app_network  

  nginx:
    build: ./nginx  
    container_name: nginx_container
    depends_on:
      - api
    ports:
      - "80:80"  
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data: 