version: '3.8'

services:
  mysql:
    image: djamka/mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todosdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - app_network

  api:
    image: djamka/todosapi
    container_name: api_container
    depends_on:
      - mysql
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql_container;Port=3306;Database=todosdb;User=myuser;Password=mypassword;"
    networks:
      - app_network

  nginx:
    image: djamka/nginx
    container_name: nginx_container
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
